version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    networks:
      - api-network
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - db:/var/lib/postgresql/data

  db_test:
    image: postgres:latest
    container_name: postgres_test
    ports:
      - "${PG_PORT_TEST}:5432"  # Correção para usar a porta padrão do PostgreSQL
    environment:
      POSTGRES_USER: ${PG_USER_TEST}
      POSTGRES_PASSWORD: ${PG_PASSWORD_TEST}
      POSTGRES_DB: ${PG_DB_TEST}
    networks:
      - api-network
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER_TEST} -d ${PG_DB_TEST}" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - ./script-test.sql:/docker-entrypoint-initdb.d/script-test.sql
      - db_test:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - api-network
    restart: 'always'

  api:
    image: financial-api-v2:latest
    container_name: financial-api
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DB}
      PG_PORT: ${PG_PORT_DOCKER} 
      PG_HOST: db                 
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3003:3003"
    networks:
      - api-network
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src            # Mapeia o diretório local src para o diretório src no container
      - /app/node_modules          # Isso evita que o volume sobrescreva os node_modules instalados no container
    command: ["pm2-runtime", "start", "build/app.js", "--name", "financial-api"] # Inicia a aplicação com PM2

networks:
  api-network:
    driver: bridge

volumes:
  db:
  db_test:
